### ISSUE TITLE
Sprite's head cut off during walking animation

### ISSUE THREAD

**Issue by ghost** [Birch-san/touhou-walk#1]
![screenshot_20180427-195435](https://user-images.githubusercontent.com/11262717/39377310-f296219a-4a54-11e8-995d-248279f01389.png)

**Comment by Birch-san** [comment]
Ah, that's working as expected. The engine correctly blits the sprites. If you look at the spritesheet, you'll see that that's exactly how the artist drew the apex of the walk cycle:

<img alt="image" src="https://github.com/Birch-san/touhou-walk/raw/master/app/src/main/res/drawable/udonge.png">
<img alt="image" src="https://github.com/Birch-san/touhou-walk/raw/master/app/src/main/res/drawable/reimu.png">
<img alt="image" src="https://github.com/Birch-san/touhou-walk/raw/master/app/src/main/res/drawable/marisa.png">

The only way to fix this would be to draw new art.
